/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BlogCloudCafe: typeof import('./src/components/Layout/Pages/blog/BlogCloudCafe.vue')['default']
    BlogConxion: typeof import('./src/components/Layout/Pages/blog/BlogConxion.vue')['default']
    BlogCyberSecChalenge2023: typeof import('./src/components/Layout/Pages/blog/BlogCyberSecChalenge2023.vue')['default']
    BlogDigitilizeFlanders: typeof import('./src/components/Layout/Pages/blog/BlogDigitilizeFlanders.vue')['default']
    BlogFirstPost: typeof import('./src/components/Layout/Pages/blog/BlogFirstPost.vue')['default']
    BlogGoogleIP: typeof import('./src/components/Layout/Pages/blog/BlogGoogleIP.vue')['default']
    BlogGoogleIPV6: typeof import('./src/components/Layout/Pages/blog/BlogGoogleIPV6.vue')['default']
    BlogHackingGarageDoorsWithRF: typeof import('./src/components/Layout/Pages/blog/BlogHackingGarageDoorsWithRF.vue')['default']
    BlogInternationaleProjectWeek: typeof import('./src/components/Layout/Pages/blog/BlogInternationaleProjectWeek.vue')['default']
    BlogSecutecSecuritySummit: typeof import('./src/components/Layout/Pages/blog/BlogSecutecSecuritySummit.vue')['default']
    BlogTemplate: typeof import('./src/components/Layout/Pages/blog/BlogTemplate.vue')['default']
    BlogTile: typeof import('./src/components/Layout/Tiles/BlogTile.vue')['default']
    Color: typeof import('./src/components/Button/Color.vue')['default']
    copy: typeof import('./src/components/Layout/Pages/blog/BlogTemplate copy.vue')['default']
    Icon: typeof import('./src/components/Button/Icon.vue')['default']
    ImageIcon: typeof import('./src/components/Button/ImageIcon.vue')['default']
    ProjectLanguage: typeof import('./src/components/Layout/General/ProjectLanguage.vue')['default']
    ProjectTile: typeof import('./src/components/Layout/Tiles/ProjectTile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionBreak: typeof import('./src/components/Layout/General/SectionBreak.vue')['default']
    SidePanel: typeof import('./src/components/SidePanel.vue')['default']
    Spacer: typeof import('./src/components/Layout/General/Spacer.vue')['default']
    Swap: typeof import('./src/components/Button/Swap.vue')['default']
    TabContent: typeof import('./src/components/Layout/Tabs/TabContent.vue')['default']
    TableGrid: typeof import('./src/components/Layout/Table/TableGrid.vue')['default']
    TabNav: typeof import('./src/components/Layout/Tabs/TabNav.vue')['default']
    TCol: typeof import('./src/components/Layout/Table/TCol.vue')['default']
    Tile: typeof import('./src/components/Layout/Tiles/Tile.vue')['default']
    TileGrid: typeof import('./src/components/Layout/Tiles/TileGrid.vue')['default']
    TRow: typeof import('./src/components/Layout/Table/TRow.vue')['default']
    Url: typeof import('./src/components/Layout/General/Url.vue')['default']
  }
}
