/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Aboutme: typeof import('./src/components/Layout/Pages/aboutme.vue')['default']
    Blog: typeof import('./src/components/Layout/Pages/blog.vue')['default']
    BlogCloudCafe: typeof import('./src/components/Layout/Pages/blog/BlogCloudCafe.vue')['default']
    BlogDigitilizeFlanders: typeof import('./src/components/Layout/Pages/blog/BlogDigitilizeFlanders.vue')['default']
    BlogInternationaleProjectWeek: typeof import('./src/components/Layout/Pages/blog/BlogInternationaleProjectWeek.vue')['default']
    BlogTemplate: typeof import('./src/components/Layout/Pages/blog/BlogTemplate.vue')['default']
    Color: typeof import('./src/components/Button/Color.vue')['default']
    Contact: typeof import('./src/components/Layout/Pages/contact.vue')['default']
    Cv: typeof import('./src/components/Layout/Pages/cv.vue')['default']
    Icon: typeof import('./src/components/Button/Icon.vue')['default']
    ImageIcon: typeof import('./src/components/Button/ImageIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidePanel: typeof import('./src/components/SidePanel.vue')['default']
    Spacer: typeof import('./src/components/Layout/General/Spacer.vue')['default']
    Swap: typeof import('./src/components/Button/Swap.vue')['default']
    TabContent: typeof import('./src/components/Layout/Tabs/TabContent.vue')['default']
    TableGrid: typeof import('./src/components/Layout/Table/TableGrid.vue')['default']
    TabNav: typeof import('./src/components/Layout/Tabs/TabNav.vue')['default']
    TCol: typeof import('./src/components/Layout/Table/TCol.vue')['default']
    Test: typeof import('./src/components/Layout/Pages/test.vue')['default']
    Tile: typeof import('./src/components/Layout/Tiles/Tile.vue')['default']
    TileGrid: typeof import('./src/components/Layout/Tiles/TileGrid.vue')['default']
    TRow: typeof import('./src/components/Layout/Table/TRow.vue')['default']
    Url: typeof import('./src/components/Layout/General/Url.vue')['default']
  }
}
